CREATE DATABASE ETEC_HAS_EX_01;
USE ETEC_HAS_EX_01;


CREATE TABLE AREA(
ID_AREA INT NOT NULL PRIMARY KEY,
NM_AREA VARCHAR (15)NOT NULL);

sp_help AREA;


CREATE TABLE PROFESSOR(
ID_PROF INT NOT NULL PRIMARY KEY,
NM_PROF VARCHAR(60) NOT NULL,
END_PROF VARCHAR(245) NOT NULL,
RG_PROF VARCHAR(20) NOT NULL,
CPF_PROF VARCHAR(12) NOT NULL);

sp_help PROFESSOR;


CREATE TABLE CURSO(
ID_CURSO INT NOT NULL PRIMARY KEY,
NM_CURSO VARCHAR(45));

sp_help CURSO;


CREATE TABLE MODULO(
ID_MOD INT NOT NULL PRIMARY KEY);

sp_help MODULO;


CREATE TABLE MATERIA(
ID_MAT INT NOT NULL PRIMARY KEY,
NM_MAT VARCHAR(50) NOT NULL);

sp_help MATERIA;


CREATE TABLE ALUNO(
ID_ALU INT NOT NULL PRIMARY KEY,
NM_ALU VARCHAR(60) NOT NULL,
END_ALU VARCHAR(255) NOT NULL,
RG_ALU VARCHAR(20) NOT NULL,
CPF_ALU varchar(11) NOT NULL,
EMAIL_ALU VARCHAR(50) NOT NULL,
NM_MAE_ALU VARCHAR(60) NOT NULL,
NM_PAI_ALU VARCHAR(60));

sp_help ALUNO;